name: Test Scraping TurismoFVG

on:
  workflow_dispatch: # Permette di avviare manualmente il workflow

jobs:
  test-scraping:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 # Specifica la versione di Python

      # Installa le dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Assicurati che il file requirements.txt sia completo

      # Esegui lo script di scraping
      - name: Run scraping_turismofvg.py
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        run: |
          python scraping_turismofvg.py
